title: Incredible
author: Rafael De Luna
email: rafael24b00@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my new site where I am testing the functioning of Github Pages
# social links
twitter_username: your-twitter-handle
github_username: [RDLL](https://github.com/RDLL)

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
